import streamlit as st
import json
from pathlib import Path
from datetime import datetime
import uuid
import time

st.set_page_config(page_title="Blossom and Nandika's Bakery Delights", layout="centered",initial_sidebar_state="expanded")
st.title("Blossom and Nandika's Bakery Delights")

if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False

if "user" not in st.session_state:
    st.session_state["user"] = None

if "role" not in st.session_state:
    st.session_state["role"] = None

if "page" not in st.session_state:
    st.session_state["page"] = "login"

if "messages" not in st.session_state:
    st.session_state["messages"] = [
        {
            "role": "Assistant",
            "content": "Hi! How can I help you?"
        }
    ]

json_inv = Path("inventory.json")
if json_inv.exists():
    with open(json_inv, "r") as f:
        inventory = json.load(f)

json_user = Path("users.json")
if json_user.exists():
    with open(json_user, "r") as f:
        users = json.load(f)

json_order = Path("orders.json")
if json_order.exists():
    with open(json_order, "r") as f:
        orders = json.load(f)

    if st.button("Login as Owner", key="owner_btn",type="primary",use_container_width=True):
        st.session_state["page"] = "Owner"
        st.rerun()

if st.session_state['role'] == 'Customer':
    if st.session_state['page'] == 'Home':
        st.markdown('Welcome! This is the Customer Dashboard!')
        st.markdown("## Here, you can browse our delicious bakery items and place your orders!")
        if st.button("Login as Customer", key="customer_btn",type="primary",use_container_width=True):
            st.session_state["page"] = "Customer"
            st.rerun()

        tab1, tab2, tab3 = st.tabs(["Add New Order", "Cancel an Order"])
        
        with tab1:
            col1, col2 = st.columns([3,3])
            with col1:
                selected_item = st.selectbox("Items", options=inventory, key= "inventory_selector",
                                        format_func= lambda x: f"{x['name']}")
            quantity = st.number_input("Enter the Quantity", min_value= 1, step=1)

            if st.button("Create New Order", key="create_order_btn", type="primary", use_container_width=True):
                with st.spinner("Recording the new order..."):
                    total = quantity * selected_item["unit_price"]

                    for item in inventory:
                        if item["item_id"] == selected_item["item_id"]:
                            item["stock"] = item["stock"] - quantity
                            break
                    
                    orders.append({
                        "id": str(uuid.uuid4()),
                        "item_id": selected_item["item_id"],
                        "quantity": quantity,
                        "status": "placed",
                        "total" : total
                    })
                    

                    with open(json_path_inventory, "w") as f:
                        json.dump(inventory,f)

                    with open(json_path_orders, "w") as f:
                        json.dump(orders, f)

                    st.balloons()
                    
                    time.sleep(8)

                    st.session_state["page"] = "home"
                    st.rerun()

        with col2:
            st.subheader("AI Assistant")
            col11, col22 = st.columns([3,1])
            with col11:
                st.caption("Try asking: How do I place an order")
            with col22:
                if st.button("Clear Messages"):
                    pass
            
            with st.container(border= True, height=250):
                for message in st.session_state["messages"]:
                    with st.chat_message(message["role"]):
                        st.write(message["content"])


            user_input = st.chat_input("Ask a question....")
            if user_input:
                with st.spinner("Thinking..."):
                    st.session_state["messages"].append(
                        {
                            "role": "user",
                            "content": user_input
                        }
                    )
                    ai_respone = "I am working on it."

                    # response is generated by ai
                    st.session_state["messages"].append(
                        {
                            "role": "assistant",
                            "content": ai_respone
                        }
                    )
                    time.sleep(2)
                    st.rerun()


elif st.session_state['role'] == 'Owner':
    

else:

    # --- LOGIN --
    st.subheader("Log In")
    with st.container(border=True):
        email_input = st.text_input("Email", key= "email_login")
        password_input = st.text_input("Password", type="password",key="password_login")
        
        if st.button("Log In", type="primary", use_container_width=True):
            with st.spinner("Logging in..."):
                time.sleep(2) # Fake backend delay
                
                # Find user
                found_user = None
                for user in users:
                    if user["email"].strip().lower() == email_input.strip().lower() and user["password"] == password_input:
                        found_user = user
                        break
                
                if found_user:
                    st.success(f"Welcome back, {found_user['email']}!")
                    st.session_state["logged_in"] = True
                    st.session_state["user"] = found_user
                    st.session_state["role"] = found_user["role"]
                    st.session_state["page"] = "home"


                    time.sleep(2)
                    st.rerun()
                else:
                    st.error("Invalid credentials")

    # --- REGISTRATION ---
    st.subheader("New Customer Account")
    with st.container(border=True):
        new_email = st.text_input("Email", key= "email_register")
        new_password = st.text_input("Password", type="password", key= "password_edit")
        
        if st.button("Create Account", key= "register_btn"):
            with st.spinner("Creating account..."):
                time.sleep(2) # Fake backend delay
                # ... (Assume validation logic here) ...
                users.append({
                    "id": str(uuid.uuid4()),
                    "email": new_email,
                    "password": new_password,
                    "role": "Customer"
                })
                
                with open(json_user, "w") as f:
                    json.dump(users,f)

                st.success("Account created!")
                st.rerun()

    st.write("---")
    st.dataframe(users)

with st.sidebar:
    st.markdown("Course Manager Sidebar")
    if  st.session_state["logged_in"] == True:
        user = st.session_state["user"]
        st.markdown(f"Logged User Email: {user['email']}")






